Best School loop

diff --git a/0x04-loops_conditions_and_parsing/102-lets_parse_apache_logs b/0x04-loops_conditions_and_parsing/102-lets_parse_apache_logs
--- a/0x04-loops_conditions_and_parsing/102-lets_parse_apache_logs
+++ b/0x04-loops_conditions_and_parsing/102-lets_parse_apache_logs
@@ -1,4 +1,11 @@
 #!/usr/bin/env bash
 # parses an Apache log file and displays the IP and HTTP code for each visitor.
 
-awk '{print $1,$9}' apache-access.log
+
+if [ ! -f apache-access.log ]
+then
+    echo "Error: apache-access.log file not found."
+    exit 1
+fi
+
+awk '{print $1, $9}' apache-access.log
